---
title       : February 5, 2013
subtitle    : JHSPH Biostatistics 753 - Advanced Methods/Applied Statistics
author      : Jeffrey Leek, Assistant Professor of Biostatistics 
job         : Johns Hopkins Bloomberg School of Public Health
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : zenburn   # 
widgets     : [mathjax,bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## Feb 5

__Announcements__

1. Ravens!!!
2. How's it going with the project?

__Agenda__

1. Getting data
2. Organizing a data analysis
3. More regression
4. In class exercises


---

## Pro-tip: 

Be a finisher. The key to getting a Ph.D. (other than passing your quals) is the ability to sit down and just power through and get it done. This means sometimes you will have to work late or on a weekend. The people who are the most successful in grad school are the people that just nd a way to get it done. If it was easy...anyone would do it.



---

## Paper of the day

[Effect of Three Decades of Screening Mammography on Breast-Cancer Incidence](http://www.nejm.org/doi/full/10.1056/NEJMoa1206809#t=article)

"After excluding the transient excess incidence associated with hormone-replacement therapy and adjusting for trends in the incidence of breast cancer among women younger than 40 years of age, we estimated that breast cancer was overdiagnosed (i.e., tumors were detected on screening that would never have led to clinical symptoms) in 1.3 million U.S. women in the past 30 years." 

[Cancer Survivor of Victim of Overdiagnosis](http://www.nytimes.com/2012/11/22/opinion/cancer-survivor-or-victim-of-overdiagnosis.html)

[Can Cancer Be Ignored](http://www.nytimes.com/2011/10/09/magazine/can-cancer-ever-be-ignored.html?_r=1&ref=magazine)

[Hopkins IHI](http://web.jhu.edu/administration/provost/initiatives/ihi/)

