---
title       : March 5, 2013
subtitle    : JHSPH Biostatistics 753 - Advanced Methods/Applied Statistics
author      : Jeffrey Leek, Assistant Professor of Biostatistics 
job         : Johns Hopkins Bloomberg School of Public Health
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : zenburn   # 
widgets     : [mathjax,bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## Mar 5

__Announcements__

1.How were the guest lectures?
2.Will try to get your results back to you


__Agenda__

1. In class
2. Bootstrap


---

## Summary feedback (part 1)

1. Describe the x and y axis, what lines/points mean, and any trends that the plot is trying to communicate. 

2. Describe in concrete (read mathematical) terms the model that you are fitting. 

3. Report estimates, interpret the estimates, report measures of uncertainty on a scientific scale (read: confidence intervals/standard errors), and measures of statistical significance. 

4. If you use statistical methods that you haven't learned in this course that is great! But please write down the model you are applying rather than reference another text.

---

## Summary feedback (part 2)

5. Do not include raw output from R (or any other programming language) directly in the write-up of a report.

6. Do not forget to answer specific questions. Even if one question is easier to answer/more interesting - be sure you provide a quantitative answer for every question asked. 

[Qual checklist](https://docs.google.com/document/d/10z0Y69EfYRohTfw7qwNPqVSEH6hbewm4_q3Gsaxq93w/edit)


---

## Pro-tip: 

When deciding on credit:

1. It should pass the embarrassment test - are you embarrassed at how much credit you got?
2. It is usually better to err on the side of sharing credit. 



---

## Paper(s) of the day


[Confidence limits on phylogenies: an approach using the bootstrap](http://www.jstor.org/discover/10.2307/2408678?uid=3739704&uid=2&uid=4&uid=3739256&sid=21101908224957)

[Bootstrap methods: another look at the jackknife](http://projecteuclid.org/DPubS?service=UI&version=1.0&verb=Display&handle=euclid.aos/1176344552)

[Bootstrapping and subsampling](http://normaldeviate.wordpress.com/2013/01/19/bootstrapping-and-subsampling-part-i/)

