---
title       : January 29 intro
subtitle    : JHSPH Biostatistics 753 - Advanced Methods/Applied Statistics
author      : Jeffrey Leek, Assistant Professor of Biostatistics 
job         : Johns Hopkins Bloomberg School of Public Health
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : zenburn   # 
widgets     : [mathjax,bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## January 29

__Announcements__

1. First assignment is up, it is due Feb. 12th at 10:30am
2. Email title format: "753 - [name of assignment] - [last name]"
  * "753 - data analysis assignment 1 - leek"
  

__Agenda__

1. Talk about in-class project
2. Parameters and randomness
3. Start working on data analysis one.


---

## Pro-tip: Simple models complex data

In data analysis - particularly for complex high-dimensional
data - it is frequently better to choose simple models for clearly defined parameters. With a lot of data, there is a strong temptation to go overboard with statistically complicated models; the danger of overfitting/ over-interpreting is extreme. The most reproducible results are often produced by sensible and statistically "simple" analyses (Note: being sensible and simple does not always lead to higher prole results).

[Beware ridiculograms!](http://www.youtube.com/watch?v=
YS-asmU3p_4&feature=channel_video_title) 

[The unreasonable effectiveness of data](https://www.youtube.com/watch?v=yvDCzhbjYWs)

---

## Paper of the day


"Classifier technology and the illusion of progress"

[http://arxiv.org/pdf/math/0606441.pdf](http://arxiv.org/pdf/math/0606441.pdf)
