---
title       : March 12, 2013
subtitle    : JHSPH Biostatistics 753 - Advanced Methods/Applied Statistics
author      : Jeffrey Leek, Assistant Professor of Biostatistics 
job         : Johns Hopkins Bloomberg School of Public Health
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : zenburn   # 
widgets     : [mathjax,bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## Mar 12

__Announcements__

1.Assignment feedback out tonight
2.Final projects due next Tuesday


__Agenda__


1. In class project
2. Hypothesis testing
3. Bootstrap hypothesis testing

---

## Pro tip

Everyone makes mistakes. Research is hard and it is messy. So you will make mistakes. The way to respond to a mistake is not to be defensive. You should acknowledge, correct, and move on. 

"Now, we scientists … take it for granted that it is perfectly consistent to be unsure — that it is possible to live and not know. But I don’t know whether everyone realizes that this is true. Our freedom to doubt was born of a struggle against authority in the early days of science. It was a very deep and strong struggle. Permit us to question — to doubt, that’s all — not to be sure. And I think it is important that we do not forget the importance of this struggle and thus perhaps lose what we have gained. Here lies a responsibility to society." - Feynman

[http://www.brainpickings.org/index.php/2013/03/06/richard-feynman-responsibility-of-scientists/](http://www.brainpickings.org/index.php/2013/03/06/richard-feynman-responsibility-of-scientists/)

---

## Paper of the day

[TThe future of data analysis (1962)](http://www.stanford.edu/~gavish/documents/Tukey_the_future_of_data_analysis.pdf)

`...organized techniques of dealing with "outliers", "wild shots", "blunders", or "large deviations" has lagged far behind both the needs...'

`We should seek wholly new questions to be answered'

`We need to tackle old probelms in more realistic frameworks'

`Data analysis must seek for scope and usefulness rather than security'



[Course website](http://jtleek.github.com/jhsph753/)
