Collect data for data analysis assignment 2
========================================================

Get my profile info
```{r}
library(rga)
rga.open(instance="ga")
profiles <- ga$getProfiles()
```

Download the data

```{r}
visitsTumblr <- ga$getData("50272379",
                                    start.date = "2011-01-01",
                                    end.date = "2013-02-14",
                                    metrics = "ga:visits",
                                    filters = "",
                                    dimensions = "ga:date",
                                    max = 1500,
                                    sort = "ga:date")

visitsTumblrTwitter <- ga$getData("50272379",
                                    start.date = "2011-01-01",
                                    end.date = "2013-02-14",
                                    metrics = "ga:visits",
                                    filters = "ga:medium==referral;ga:source==t.co",
                                    dimensions = "ga:date",
                                    max = 1500,
                                    sort = "ga:date")


visitsWordpress <- ga$getData("66228613",
                                    start.date = "2011-01-01",
                                    end.date = "2013-02-14",
                                    metrics = "ga:visits",
                                    filters = ""l,
                                    dimensions = "ga:date",
                                    max = 1500,
                                    sort = "ga:date")

visitsWordpressTwitter <- ga$getData("66228613",
                                    start.date = "2011-01-01",
                                    end.date = "2013-02-14",
                                    metrics = "ga:visits",
                                    filters = "ga:medium==referral;ga:source==t.co",
                                    dimensions = "ga:date",
                                    max = 1500,
                                    sort = "ga:date")

gaData <- data.frame(date=visitsWordpress[,1],visitsTumblr=visitsTumblr[,2],visitsWordpress=visitsWordpress[,2],visitsTumblrTwitter=visitsTumblrTwitter[,2],visitsWordpressTwitter=visitsWordpressTwitter[,2])

```
