---
title       : March 14, 2013
subtitle    : JHSPH Biostatistics 753 - Advanced Methods/Applied Statistics
author      : Jeffrey Leek, Assistant Professor of Biostatistics 
job         : Johns Hopkins Bloomberg School of Public Health
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : zenburn   # 
widgets     : [mathjax,bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## Mar 14

__Announcements__

1. Happy [Pi Day](http://en.wikipedia.org/wiki/Pi_Day)!!!
2. Finals due next Tuesday

__Agenda__


1.Finish single testing
2.Multiple testing

---

## Pro tip

Ways to come up with a new method:
* A new data type - new method
* A new data type - adapt old method
* An overlooked problem
* Changing the assumptions of a current method
* Generalizing a known method



---

## Paper of the day

[Controlling the false discovery rate: a practical and powerful approach to multiple testing](http://www.stat.purdue.edu/~doerge/BIOINFORM.D/FALL06/Benjamini%20and%20Y%20FDR.pdf)
[Statistical significance for genomewide studies](http://www.pnas.org/content/100/16/9440.full)


---

## Key statistical concepts from this term

* Organizing a data analysis
* What do we mean by "randomness"
* How to get data (from the web/in person)
* Estimating equations and least squares
* Sandwich estimation for variances
* GLMs (link functions, parametric families, iteratively re-weighted least squares)
* Plotting basics

---

## Key statistical concepts from this term


* Clustering basics (kmeans,heirarchical clustering)
* Smoothing (very basics)
* SVD
* Bootstrap
* Hypothesis testing
* Multiple testing

---

## Key non-statistical concepts from this term

* Reading the literature
* Data analyis is not just statistics/math
* Data analysis is not just coding
* Data analysis requires careful writing/interpretation
* __You will learn a tiny fraction of what you need to know in class__
* __Self-starting is a hugely valued character trait in this biz__

---

## How to think about developing a method

__Hopefully the in-class projects suggested__

* See some data
* Quantify the problem
* Start simple
* Talk to some people
* Write down a procedure
* Code it up
* Test it out
* Iterate

---

## Preview of next term

* More high-dimensional stuff
* More smoothing
* Alternative uses of things like GLMs
* GEEs/dependent data
* Simulation studies/sensitivy analysis
* Prediction
* Maybe GAMs, graphical models, basics of causal stuff...


[Course website](http://jtleek.github.com/jhsph753/)
